In [0]:
raw_orders = ["  ORD100:Electronics:250.50  ", "  ORD101:Apparel:45.00  ", "  ORD102:Electronics:invalid  ", "  ORD103:Home:-10.0  "]
config = {"min_threshold": 0.0, "currency": "USD"}

### Sub-task 2: String Sanitization
Create an empty list called `cleaned_orders`. Loop through `raw_orders`, strip whitespaces, and convert them to uppercase.

* **Expected Result:** `['ORD100:ELECTRONICS:250.50', 'ORD101:APPAREL:45.00', 'ORD102:ELECTRONICS:INVALID', 'ORD103:HOME:-10.0']`

In [0]:
cleaned_orders = [order.strip().upper() for order in raw_orders]
print(cleaned_orders)

['ORD100:ELECTRONICS:250.50', 'ORD101:APPAREL:45.00', 'ORD102:ELECTRONICS:INVALID', 'ORD103:HOME:-10.0']


### Sub-task 3: Parsing and Type Conversion
Iterate through `cleaned_orders`. Split each string by `:`. 
Try to convert the price (the third element) to a float. If it fails (e.g., "INVALID"), skip that record using `continue`.

* **Expected Result:** (Filtered list of components in memory)

In [0]:
parsed_records = []
for order in cleaned_orders:
    parts = order.split(":")
    try:
        parts[2] = float(parts[2])
        parsed_records.append(parts)
    except ValueError:
        print(f"skipping : {parts[0]}")
        continue

skipping : ORD102


### Sub-task 4: Business Logic Validation
From the `parsed_records`, remove any order where the price is less than or equal to `config["min_threshold"]`.

* **Expected Result:** `[['ORD100', 'ELECTRONICS', 250.5], ['ORD101', 'APPAREL', 45.0]]`

In [0]:
valid_records = []
for order in parsed_records:
    if order[2] >= config["min_threshold"]:
        valid_records.append(order)
print(valid_records)

[['ORD100', 'ELECTRONICS', 250.5], ['ORD101', 'APPAREL', 45.0]]


### Sub-task 5: Dictionary Transformation
Convert the `valid_records` list into a list of dictionaries with keys: `id`, `category`, and `price`.

* **Expected Result:** `[{'id': 'ORD100', 'category': 'ELECTRONICS', 'price': 250.5}, {'id': 'ORD101', 'category': 'APPAREL', 'price': 45.0}]`

In [0]:
order_dicts = []
for order in valid_records:
    order_dict = {
        "id": order[0],
        "category": order[1],
        "price": order[2],
    }
    order_dicts.append(order_dict)
print(order_dicts)

[{'id': 'ORD100', 'category': 'ELECTRONICS', 'price': 250.5}, {'id': 'ORD101', 'category': 'APPAREL', 'price': 45.0}]


### Sub-task 6: Category Aggregation (Sets)
Extract all unique categories from `order_dicts` using a set.

* **Expected Result:** `{'ELECTRONICS', 'APPAREL'}`

In [0]:
unique_categories = set()
for order in order_dicts :
    unique_categories.add(order["category"])
print(unique_categories)

{'ELECTRONICS', 'APPAREL'}


### Sub-task 7: Discount Calculation
For every order in the "ELECTRONICS" category, apply a 10% discount to the price. Round to 2 decimals.

* **Expected Result:** Price for ORD100 becomes `225.45`

In [0]:
for order in order_dicts :
        if order["category"] == "ELECTRONICS":
            elec_price = order["price"]*0.9
            order["price"] = round(elec_price,2)
print(order_dicts)

[{'id': 'ORD100', 'category': 'ELECTRONICS', 'price': 225.45}, {'id': 'ORD101', 'category': 'APPAREL', 'price': 45.0}]


### Sub-task 8: Summary Statistics
Calculate the total revenue of all orders in `order_dicts`.

* **Expected Result:** `270.45` (225.45 + 45.0)

In [0]:
total_revenue = sum(order["price"] for order in order_dicts)
print(total_revenue)

270.45


### Sub-task 9: Final Reporting
Using a loop and `enumerate`, print a final report for each order in the format: 
`Item 1: [ID] - [PRICE] USD`

* **Expected Result:**
`Item 1: ORD100 - 225.45 USD`
`Item 2: ORD101 - 45.0 USD`

In [0]:
for index , order in enumerate(order_dicts , start = 1) :
    id = order["id"]
    price = order["price"]
    print(f"Item{index} : {id} - {price} USD" )


Item1 : ORD100 - 225.45 USD
Item2 : ORD101 - 45.0 USD


### Sub-task 10: System Log & Cleanup
Add a `status` key to the `config` dictionary with the value `"Complete"`. Clear the `raw_orders` list to save memory.

* **Expected Result:**
`config: {'min_threshold': 0.0, 'currency': 'USD', 'status': 'Complete'}`
`raw_orders: []`

In [0]:
config["status"] = "complete"
raw_orders.clear()
print(f"config : {config} , raw_orders : {raw_orders}")

config : {'min_threshold': 0.0, 'currency': 'USD', 'status': 'complete'} , raw_orders : []
